// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'Features/ahadith/domain/entities/hadith_entity.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
      id: const obx_int.IdUid(1, 1339134150720436132),
      name: 'HadithEntity',
      lastPropertyId: const obx_int.IdUid(6, 573035456028332893),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 8018149208905831867),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 7069280207203469334),
            name: 'hadith',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 7122846280678515386),
            name: 'hadithNumber',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 9003882839765075204),
            name: 'bookName',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 3853074909933021227),
            name: 'sectionOfBookHadith',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 573035456028332893),
            name: 'gradesJson',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[])
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore(
    {String? directory,
    int? maxDBSizeInKB,
    int? maxDataSizeInKB,
    int? fileMode,
    int? maxReaders,
    bool queriesCaseSensitiveDefault = true,
    String? macosApplicationGroup}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(getObjectBoxModel(),
      directory: directory ?? (await defaultStoreDirectory()).path,
      maxDBSizeInKB: maxDBSizeInKB,
      maxDataSizeInKB: maxDataSizeInKB,
      fileMode: fileMode,
      maxReaders: maxReaders,
      queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
      macosApplicationGroup: macosApplicationGroup);
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
      entities: _entities,
      lastEntityId: const obx_int.IdUid(1, 1339134150720436132),
      lastIndexId: const obx_int.IdUid(0, 0),
      lastRelationId: const obx_int.IdUid(0, 0),
      lastSequenceId: const obx_int.IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, obx_int.EntityDefinition>{
    HadithEntity: obx_int.EntityDefinition<HadithEntity>(
        model: _entities[0],
        toOneRelations: (HadithEntity object) => [],
        toManyRelations: (HadithEntity object) => {},
        getId: (HadithEntity object) => object.id,
        setId: (HadithEntity object, int id) {
          object.id = id;
        },
        objectToFB: (HadithEntity object, fb.Builder fbb) {
          final hadithOffset = fbb.writeString(object.hadith);
          final hadithNumberOffset = fbb.writeString(object.hadithNumber);
          final bookNameOffset = fbb.writeString(object.bookName);
          final sectionOfBookHadithOffset =
              fbb.writeString(object.sectionOfBookHadith);
          final gradesJsonOffset = fbb.writeString(object.gradesJson);
          fbb.startTable(7);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, hadithOffset);
          fbb.addOffset(2, hadithNumberOffset);
          fbb.addOffset(3, bookNameOffset);
          fbb.addOffset(4, sectionOfBookHadithOffset);
          fbb.addOffset(5, gradesJsonOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final hadithParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final bookNameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 10, '');
          final sectionOfBookHadithParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 12, '');
          final hadithNumberParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 8, '');
          final gradesJsonParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 14, '');
          final object = HadithEntity(
              hadith: hadithParam,
              bookName: bookNameParam,
              sectionOfBookHadith: sectionOfBookHadithParam,
              hadithNumber: hadithNumberParam,
              gradesJson: gradesJsonParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

          return object;
        })
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [HadithEntity] entity fields to define ObjectBox queries.
class HadithEntity_ {
  /// See [HadithEntity.id].
  static final id =
      obx.QueryIntegerProperty<HadithEntity>(_entities[0].properties[0]);

  /// See [HadithEntity.hadith].
  static final hadith =
      obx.QueryStringProperty<HadithEntity>(_entities[0].properties[1]);

  /// See [HadithEntity.hadithNumber].
  static final hadithNumber =
      obx.QueryStringProperty<HadithEntity>(_entities[0].properties[2]);

  /// See [HadithEntity.bookName].
  static final bookName =
      obx.QueryStringProperty<HadithEntity>(_entities[0].properties[3]);

  /// See [HadithEntity.sectionOfBookHadith].
  static final sectionOfBookHadith =
      obx.QueryStringProperty<HadithEntity>(_entities[0].properties[4]);

  /// See [HadithEntity.gradesJson].
  static final gradesJson =
      obx.QueryStringProperty<HadithEntity>(_entities[0].properties[5]);
}
